# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: landing_target/landing_target.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import mavsdk_options_pb2 as mavsdk__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#landing_target/landing_target.proto\x12\x19mavsdk.rpc.landing_target\x1a\x14mavsdk_options.proto\"0\n\rPositionLocal\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"b\n\x1ePublishPositionRelativeRequest\x12@\n\x0eposition_local\x18\x01 \x01(\x0b\x32(.mavsdk.rpc.landing_target.PositionLocal\"p\n\x1fPublishPositionRelativeResponse\x12M\n\x15landing_target_result\x18\x01 \x01(\x0b\x32..mavsdk.rpc.landing_target.LandingTargetResult\"\xb8\x01\n\x13LandingTargetResult\x12\x45\n\x06result\x18\x01 \x01(\x0e\x32\x35.mavsdk.rpc.landing_target.LandingTargetResult.Result\x12\x12\n\nresult_str\x18\x02 \x01(\t\"F\n\x06Result\x12\x12\n\x0eRESULT_UNKNOWN\x10\x00\x12\x12\n\x0eRESULT_SUCCESS\x10\x01\x12\x14\n\x10RESULT_NO_SYSTEM\x10\x02\x32\xaf\x01\n\x14LandingTargetService\x12\x96\x01\n\x17PublishPositionRelative\x12\x39.mavsdk.rpc.landing_target.PublishPositionRelativeRequest\x1a:.mavsdk.rpc.landing_target.PublishPositionRelativeResponse\"\x04\x80\xb5\x18\x01\x42.\n\x18io.mavsdk.landing_targetB\x12LandingTargetProtob\x06proto3')



_POSITIONLOCAL = DESCRIPTOR.message_types_by_name['PositionLocal']
_PUBLISHPOSITIONRELATIVEREQUEST = DESCRIPTOR.message_types_by_name['PublishPositionRelativeRequest']
_PUBLISHPOSITIONRELATIVERESPONSE = DESCRIPTOR.message_types_by_name['PublishPositionRelativeResponse']
_LANDINGTARGETRESULT = DESCRIPTOR.message_types_by_name['LandingTargetResult']
_LANDINGTARGETRESULT_RESULT = _LANDINGTARGETRESULT.enum_types_by_name['Result']
PositionLocal = _reflection.GeneratedProtocolMessageType('PositionLocal', (_message.Message,), {
  'DESCRIPTOR' : _POSITIONLOCAL,
  '__module__' : 'landing_target.landing_target_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.landing_target.PositionLocal)
  })
_sym_db.RegisterMessage(PositionLocal)

PublishPositionRelativeRequest = _reflection.GeneratedProtocolMessageType('PublishPositionRelativeRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHPOSITIONRELATIVEREQUEST,
  '__module__' : 'landing_target.landing_target_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.landing_target.PublishPositionRelativeRequest)
  })
_sym_db.RegisterMessage(PublishPositionRelativeRequest)

PublishPositionRelativeResponse = _reflection.GeneratedProtocolMessageType('PublishPositionRelativeResponse', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHPOSITIONRELATIVERESPONSE,
  '__module__' : 'landing_target.landing_target_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.landing_target.PublishPositionRelativeResponse)
  })
_sym_db.RegisterMessage(PublishPositionRelativeResponse)

LandingTargetResult = _reflection.GeneratedProtocolMessageType('LandingTargetResult', (_message.Message,), {
  'DESCRIPTOR' : _LANDINGTARGETRESULT,
  '__module__' : 'landing_target.landing_target_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.landing_target.LandingTargetResult)
  })
_sym_db.RegisterMessage(LandingTargetResult)

_LANDINGTARGETSERVICE = DESCRIPTOR.services_by_name['LandingTargetService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030io.mavsdk.landing_targetB\022LandingTargetProto'
  _LANDINGTARGETSERVICE.methods_by_name['PublishPositionRelative']._options = None
  _LANDINGTARGETSERVICE.methods_by_name['PublishPositionRelative']._serialized_options = b'\200\265\030\001'
  _POSITIONLOCAL._serialized_start=88
  _POSITIONLOCAL._serialized_end=136
  _PUBLISHPOSITIONRELATIVEREQUEST._serialized_start=138
  _PUBLISHPOSITIONRELATIVEREQUEST._serialized_end=236
  _PUBLISHPOSITIONRELATIVERESPONSE._serialized_start=238
  _PUBLISHPOSITIONRELATIVERESPONSE._serialized_end=350
  _LANDINGTARGETRESULT._serialized_start=353
  _LANDINGTARGETRESULT._serialized_end=537
  _LANDINGTARGETRESULT_RESULT._serialized_start=467
  _LANDINGTARGETRESULT_RESULT._serialized_end=537
  _LANDINGTARGETSERVICE._serialized_start=540
  _LANDINGTARGETSERVICE._serialized_end=715
# @@protoc_insertion_point(module_scope)
