# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: precision_target/precision_target.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import mavsdk_options_pb2 as mavsdk__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'precision_target/precision_target.proto\x12\x1bmavsdk.rpc.precision_target\x1a\x14mavsdk_options.proto\"0\n\rPositionLocal\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"d\n\x1ePublishPositionRelativeRequest\x12\x42\n\x0eposition_local\x18\x01 \x01(\x0b\x32*.mavsdk.rpc.precision_target.PositionLocal\"v\n\x1fPublishPositionRelativeResponse\x12S\n\x17precision_target_result\x18\x01 \x01(\x0b\x32\x32.mavsdk.rpc.precision_target.PrecisionTargetResult\"\xbe\x01\n\x15PrecisionTargetResult\x12I\n\x06result\x18\x01 \x01(\x0e\x32\x39.mavsdk.rpc.precision_target.PrecisionTargetResult.Result\x12\x12\n\nresult_str\x18\x02 \x01(\t\"F\n\x06Result\x12\x12\n\x0eRESULT_UNKNOWN\x10\x00\x12\x12\n\x0eRESULT_SUCCESS\x10\x01\x12\x14\n\x10RESULT_NO_SYSTEM\x10\x02\x32\xb5\x01\n\x16PrecisionTargetService\x12\x9a\x01\n\x17PublishPositionRelative\x12;.mavsdk.rpc.precision_target.PublishPositionRelativeRequest\x1a<.mavsdk.rpc.precision_target.PublishPositionRelativeResponse\"\x04\x80\xb5\x18\x01\x42\x32\n\x1aio.mavsdk.precision_targetB\x14PrecisionTargetProtob\x06proto3')



_POSITIONLOCAL = DESCRIPTOR.message_types_by_name['PositionLocal']
_PUBLISHPOSITIONRELATIVEREQUEST = DESCRIPTOR.message_types_by_name['PublishPositionRelativeRequest']
_PUBLISHPOSITIONRELATIVERESPONSE = DESCRIPTOR.message_types_by_name['PublishPositionRelativeResponse']
_PRECISIONTARGETRESULT = DESCRIPTOR.message_types_by_name['PrecisionTargetResult']
_PRECISIONTARGETRESULT_RESULT = _PRECISIONTARGETRESULT.enum_types_by_name['Result']
PositionLocal = _reflection.GeneratedProtocolMessageType('PositionLocal', (_message.Message,), {
  'DESCRIPTOR' : _POSITIONLOCAL,
  '__module__' : 'precision_target.precision_target_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.precision_target.PositionLocal)
  })
_sym_db.RegisterMessage(PositionLocal)

PublishPositionRelativeRequest = _reflection.GeneratedProtocolMessageType('PublishPositionRelativeRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHPOSITIONRELATIVEREQUEST,
  '__module__' : 'precision_target.precision_target_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.precision_target.PublishPositionRelativeRequest)
  })
_sym_db.RegisterMessage(PublishPositionRelativeRequest)

PublishPositionRelativeResponse = _reflection.GeneratedProtocolMessageType('PublishPositionRelativeResponse', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHPOSITIONRELATIVERESPONSE,
  '__module__' : 'precision_target.precision_target_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.precision_target.PublishPositionRelativeResponse)
  })
_sym_db.RegisterMessage(PublishPositionRelativeResponse)

PrecisionTargetResult = _reflection.GeneratedProtocolMessageType('PrecisionTargetResult', (_message.Message,), {
  'DESCRIPTOR' : _PRECISIONTARGETRESULT,
  '__module__' : 'precision_target.precision_target_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.precision_target.PrecisionTargetResult)
  })
_sym_db.RegisterMessage(PrecisionTargetResult)

_PRECISIONTARGETSERVICE = DESCRIPTOR.services_by_name['PrecisionTargetService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032io.mavsdk.precision_targetB\024PrecisionTargetProto'
  _PRECISIONTARGETSERVICE.methods_by_name['PublishPositionRelative']._options = None
  _PRECISIONTARGETSERVICE.methods_by_name['PublishPositionRelative']._serialized_options = b'\200\265\030\001'
  _POSITIONLOCAL._serialized_start=94
  _POSITIONLOCAL._serialized_end=142
  _PUBLISHPOSITIONRELATIVEREQUEST._serialized_start=144
  _PUBLISHPOSITIONRELATIVEREQUEST._serialized_end=244
  _PUBLISHPOSITIONRELATIVERESPONSE._serialized_start=246
  _PUBLISHPOSITIONRELATIVERESPONSE._serialized_end=364
  _PRECISIONTARGETRESULT._serialized_start=367
  _PRECISIONTARGETRESULT._serialized_end=557
  _PRECISIONTARGETRESULT_RESULT._serialized_start=487
  _PRECISIONTARGETRESULT_RESULT._serialized_end=557
  _PRECISIONTARGETSERVICE._serialized_start=560
  _PRECISIONTARGETSERVICE._serialized_end=741
# @@protoc_insertion_point(module_scope)
